name: Deploy Website

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Deployment
        run: |
          ssh \
            -p 522 \
            -o StrictHostKeyChecking=no \
            -i ~/.ssh/id_ed25519 \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_ed25519 \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}
